name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.2

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 18.18

    - name: Install dependencies
      run: npm ci
    # 
    # - name: Build TypeScript
    #   run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Get current date and time
      id: datetime
      run: echo "DATETIME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/web-integrations-template:latest
          ghcr.io/${{ github.repository_owner }}/web-integrations-template:${{ env.DATETIME }}
